# Generated by Django 5.0.2 on 2024-02-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('COMIDA', 'Comida'), ('BEBIDA', 'Bebida')], max_length=50)),
                ('thumb_img', models.ImageField(default='', upload_to='thumb_foods')),
            ],
        ),
    ]
