# Generated by Django 5.0.2 on 2024-02-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('COMIDA', 'Comida'), ('BEBIDA', 'Bebida'), ('DRINKS', 'Drinks'), ('PRATO PRINCIPAL', 'Prato Principal'), ('SOBREMESA', 'Sobremesa')], max_length=50),
        ),
    ]
